-- Add cover_letter_count column to usage_quotas table
-- This migration adds quota tracking for cover letter generation

ALTER TABLE usage_quotas 
ADD COLUMN IF NOT EXISTS cover_letter_count INTEGER DEFAULT 0;

-- Update existing rows to have 0 as default
UPDATE usage_quotas 
SET cover_letter_count = 0 
WHERE cover_letter_count IS NULL;

-- Add comment for documentation
COMMENT ON COLUMN usage_quotas.cover_letter_count IS 'Number of cover letters generated by the user. Free plan limit: 3';
